import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="touch-[pan-x_pan-y] overscroll-contain"
    >
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </head>
      <body className={` ${lato.className} antialiased`}>
        <Navbar />
        {children}
        <div className="flex flex-col mt-[100] md:mt-[150px]">

        <Footer />
        </div>
      </body>
    </html>
  );
}
